# Generated by Django 4.0.2 on 2022-03-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('username', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=14)),
                ('maxconn', models.IntegerField(default=1)),
                ('bouquet', models.CharField(max_length=50)),
            ],
        ),
    ]
