# Generated by Django 4.0.3 on 2022-03-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermng', '0004_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='ipadd',
            field=models.CharField(max_length=15),
        ),
    ]
