# Generated by Django 4.0.3 on 2022-03-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermng', '0005_alter_sucursal_ipadd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='ipadd',
            new_name='ipaddress',
        ),
    ]
