# Generated by Django 4.0.3 on 2022-03-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermng', '0007_sucursal_operators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='operators',
            field=models.CharField(default='isranyag', max_length=200),
        ),
    ]
