# Generated by Django 4.0.3 on 2022-03-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermng', '0009_sucursal_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='port',
            field=models.PositiveIntegerField(),
        ),
    ]
