# Generated by Django 4.0.3 on 2022-03-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_sucursal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
